name: BIST Scanner

on:
  schedule:
    # Hafta içi (1-5), TR saatiyle 10:00 - 18:15 arası (UTC 07:00 - 15:15)
    - cron: "*/15 7-15 * * 1-5"

  workflow_dispatch:

jobs:
  run-scanner:

    runs-on: ubuntu-latest


    steps:

      - name: Repo cek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Kütüphaneleri kur
        run: |
          pip install pandas numpy requests websocket-client
          pip install git+https://github.com/rongardF/tvdatafeed.git

      - name: Scanner çalıştır
        run: |
          python scanner.py


