name: BIST Scanner

on:
  
  workflow_dispatch:

jobs:
  run-scanner:

    runs-on: ubuntu-latest


    steps:

      - name: Repo cek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Kütüphaneleri kur
        run: |
          pip install pandas numpy requests websocket-client
          pip install git+https://github.com/rongardF/tvdatafeed.git

      - name: Scanner çalıştır
        run: |
          python scanner.py

- name: Hafızayı Kaydet (Commit)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add hafiza.json
          git commit -m "Hafiza guncellendi" || echo "Degisiklik yok"
          git push
